name: decoder-only-transformer
channels:
  - pytorch-nightly
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=openblas
  - brotli-python=1.0.9=py312h313beb8_7
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2023.12.12=hca03da5_0
  - certifi=2023.11.17=py312hca03da5_0
  - cffi=1.16.0=py312h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py312hd4332d6_0
  - expat=2.5.0=h313beb8_0
  - filelock=3.13.1=py312hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.1=h80987f9_3
  - idna=3.4=py312hca03da5_0
  - jinja2=3.1.2=py312hca03da5_0
  - jpeg=9e=h80987f9_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.1=py312h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.1=py312hca03da5_0
  - numpy=1.26.3=py312h7f4fdc5_0
  - numpy-base=1.26.3=py312he047099_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.12=h1a28f6b_0
  - pillow=10.0.1=py312h3b245a6_0
  - pip=23.3.1=py312hca03da5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.0=h99e199e_0
  - pytorch=2.3.0.dev20240115=py3.12_0
  - pyyaml=6.0.1=py312h80987f9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py312hca03da5_0
  - setuptools=68.2.2=py312hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.12=py312hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchaudio=2.2.0.dev20240115=py312_cpu
  - torchvision=0.18.0.dev20240115=py312_cpu
  - typing_extensions=4.7.1=py312hca03da5_0
  - tzdata=2023d=h04d1e81_0
  - urllib3=1.26.18=py312hca03da5_0
  - wheel=0.41.2=py312hca03da5_0
  - xz=5.4.5=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
